"""hu_analysis.py — HU value distribution & per-tissue error analysis.

Reviewer comment:
  "The paper does not present pixel-wise comparison results of HU values,
   which are the most critical metric for radiotherapy fidelity. Could the
   authors provide the HU value distribution histograms of the images
   generated by the 2D and 2.5D models versus the ground-truth CT images,
   as well as the statistical analysis of HU value errors for key tissues?"

Outputs (in --output_dir):
  hu_histogram.png         — HU distribution overlay (gen vs GT per model)
  hu_error_stats.csv       — MAE / RMSE / bias per model × anatomy
  hu_tissue_error_stats.csv — MAE / RMSE / bias per model × tissue type
"""
from __future__ import annotations
import argparse, pathlib
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader, random_split
from monai.utils import set_determinism
from tqdm.auto import tqdm

from data.synthrad2025 import SynthRad2025, build_transforms
from eval_full import (
    MODEL_CONFIGS, build_subj_anatomy_map,
    EMBEDDING_DIM, NUM_EMBEDDINGS, SPATIAL_SIZE,
)
from stage2_vdm import (
    load_frozen_vqvae, build_vdm,
    _prepare_cond, sample_conditional,
)

# ---------------------------------------------------------------------------
# HU conversion
# ---------------------------------------------------------------------------

HU_MIN = -1024.0
HU_MAX =  3071.0

def to_hu(x: torch.Tensor) -> torch.Tensor:
    """[0, 1] normalized → HU values."""
    return x * (HU_MAX - HU_MIN) + HU_MIN

# ---------------------------------------------------------------------------
# Tissue masks (on HU tensor)
# ---------------------------------------------------------------------------

TISSUES = {
    "Air"         : (None,  -700),   # HU < -700
    "Lung"        : (-700,  -200),
    "Fat"         : (-200,   -50),
    "Soft tissue" : ( -50,   150),
    "Bone"        : ( 150,  None),   # HU > 150
}

def tissue_mask(hu: torch.Tensor, lo: float | None, hi: float | None) -> torch.Tensor:
    mask = torch.ones_like(hu, dtype=torch.bool)
    if lo is not None:
        mask &= hu >= lo
    if hi is not None:
        mask &= hu < hi
    return mask

# ---------------------------------------------------------------------------
# Error stats helpers
# ---------------------------------------------------------------------------

def hu_errors(pred_hu: np.ndarray, gt_hu: np.ndarray) -> dict:
    err = pred_hu - gt_hu
    return {
        "mae"  : float(np.abs(err).mean()),
        "rmse" : float(np.sqrt((err ** 2).mean())),
        "bias" : float(err.mean()),
        "std"  : float(err.std()),
    }

# ---------------------------------------------------------------------------
# Which models to compare (default: all 8; can restrict via --keys)
# ---------------------------------------------------------------------------

def get_configs(keys: list[str] | None) -> list[dict]:
    if not keys:
        return MODEL_CONFIGS
    return [c for c in MODEL_CONFIGS if c["key"] in keys]

# ---------------------------------------------------------------------------
# Load model (reuses eval_full logic, but lighter — no scale_factor train loop)
# ---------------------------------------------------------------------------

def load_for_hu(cfg, data_root, ckpt_base, vqvae_base, device,
                val_ratio=0.2, seed=42, batch_size=4, num_workers=4):
    n, cpr, backbone = cfg["n"], cfg["cpr"], cfg["backbone"]

    vqvae_kw = dict(out_channels=1, compress_ratio=cpr,
                    embedding_dim=EMBEDDING_DIM, num_embeddings=NUM_EMBEDDINGS)
    ct_ae   = load_frozen_vqvae(
        f"{vqvae_base}/1_vqvae_ct_n{n}_cpr{cpr}_img128/best.pt",
        device, in_channels=n, **vqvae_kw,
    )
    cbct_ae = load_frozen_vqvae(
        f"{vqvae_base}/1_vqvae_cbct_n{n}_cpr{cpr}_img128/best.pt",
        device, in_channels=n, **vqvae_kw,
    )

    with torch.no_grad():
        dummy = torch.zeros(1, n, SPATIAL_SIZE, SPATIAL_SIZE, device=device)
        latent_shape = tuple(ct_ae.encode_stage_2_inputs(dummy).shape[1:])

    full_ds = SynthRad2025(
        root=f"{data_root}/dataset/train/n{n}",
        modality=["cbct", "ct"], anatomy=["AB", "HN", "TH"],
        transform=build_transforms(["cbct", "ct"], spatial_size=(128, 128), augment=False),
    )
    n_val   = int(len(full_ds) * val_ratio)
    n_train = len(full_ds) - n_val
    train_ds, val_ds = random_split(
        full_ds, [n_train, n_val],
        generator=torch.Generator().manual_seed(seed),
    )

    # scale_factor: 훈련과 동일하게 재현
    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=(device.type == "cuda"),
        generator=torch.Generator().manual_seed(seed),
    )
    with torch.no_grad():
        first = next(iter(train_loader))
        _z = ct_ae.encode_stage_2_inputs(first["ct"].to(device))
        scale_factor = 1.0 / _z.flatten().std().item()

    vdm = build_vdm(backbone, n, cpr, latent_shape, SPATIAL_SIZE).to(device)
    ckpt = torch.load(
        f"{ckpt_base}/1_vdm_{backbone}_n{n}_cpr{cpr}_img128/latest.pt",
        map_location=device, weights_only=False,
    )
    vdm.load_state_dict(ckpt["model_state_dict"], strict=False)
    vdm.eval()
    for p in vdm.parameters():
        p.requires_grad_(False)

    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=(device.type == "cuda"),
    )
    subj_anatomy = build_subj_anatomy_map(data_root, n)

    return dict(ct_ae=ct_ae, cbct_ae=cbct_ae, vdm=vdm,
                scale_factor=scale_factor, val_loader=val_loader,
                subj_anatomy=subj_anatomy, backbone=backbone)

# ---------------------------------------------------------------------------
# Per-model inference → collect HU arrays
# ---------------------------------------------------------------------------

@torch.no_grad()
def collect_hu(cfg, loaded, device, n_sample_steps=200):
    ct_ae        = loaded["ct_ae"]
    cbct_ae      = loaded["cbct_ae"]
    vdm          = loaded["vdm"]
    scale_factor = loaded["scale_factor"]
    val_loader   = loaded["val_loader"]
    subj_anatomy = loaded["subj_anatomy"]
    backbone     = loaded["backbone"]
    n            = cfg["n"]
    mid          = n // 2

    records = []   # {"anatomy", "pred_hu", "gt_hu"}  — per sample flat arrays

    for batch in tqdm(val_loader, desc=cfg["key"], leave=False):
        ct_img   = batch["ct"].to(device)
        cbct_img = batch["cbct"].to(device)
        subj_ids = batch["subj_id"]

        z_cond    = cbct_ae.encode_stage_2_inputs(cbct_img) * scale_factor
        cond      = _prepare_cond(z_cond, backbone)
        sampled_z = sample_conditional(vdm, cond, n_sample_steps, device)
        ct_gen    = ct_ae.decode_stage_2_outputs(sampled_z / scale_factor).float()
        ct_gt     = ct_img[:, mid:mid+1].float()

        pred_hu = to_hu(ct_gen).cpu().numpy()   # (B, 1, H, W)
        gt_hu   = to_hu(ct_gt).cpu().numpy()

        for i in range(pred_hu.shape[0]):
            sid = subj_ids[i]
            records.append({
                "anatomy" : subj_anatomy.get(sid, "UNKNOWN"),
                "pred_hu" : pred_hu[i].ravel(),
                "gt_hu"   : gt_hu[i].ravel(),
            })

    return records

# ---------------------------------------------------------------------------
# Plot: HU histogram overlay
# ---------------------------------------------------------------------------

def plot_hu_histograms(all_data: dict[str, list], output_dir: pathlib.Path):
    """all_data: {model_key: [records]}"""
    models = list(all_data.keys())
    n_models = len(models)
    bins = np.linspace(HU_MIN, HU_MAX, 200)

    fig, axes = plt.subplots(1, n_models, figsize=(5 * n_models, 4), sharey=False)
    if n_models == 1:
        axes = [axes]

    for ax, key in zip(axes, models):
        records = all_data[key]
        pred_all = np.concatenate([r["pred_hu"] for r in records])
        gt_all   = np.concatenate([r["gt_hu"]   for r in records])

        ax.hist(gt_all,   bins=bins, density=True, alpha=0.5,
                color="#2196F3", label="Ground-truth CT")
        ax.hist(pred_all, bins=bins, density=True, alpha=0.5,
                color="#F44336", label="Generated CT")
        ax.set_title(key, fontsize=9)
        ax.set_xlabel("HU value")
        ax.set_ylabel("Density")
        ax.legend(fontsize=7)

    fig.suptitle("HU Value Distribution: Generated vs Ground-truth CT", fontsize=11)
    fig.tight_layout()
    path = output_dir / "hu_histogram.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"[저장] {path}")

# ---------------------------------------------------------------------------
# Per-anatomy error stats
# ---------------------------------------------------------------------------

def compute_anatomy_stats(all_data: dict[str, list]) -> pd.DataFrame:
    rows = []
    for key, records in all_data.items():
        by_anat: dict[str, tuple[list, list]] = {}
        for r in records:
            a = r["anatomy"]
            if a not in by_anat:
                by_anat[a] = ([], [])
            by_anat[a][0].append(r["pred_hu"])
            by_anat[a][1].append(r["gt_hu"])

        for anat, (preds, gts) in by_anat.items():
            p = np.concatenate(preds)
            g = np.concatenate(gts)
            stats = hu_errors(p, g)
            rows.append({"model": key, "anatomy": anat, **stats})

    return pd.DataFrame(rows)

# ---------------------------------------------------------------------------
# Per-tissue error stats
# ---------------------------------------------------------------------------

def compute_tissue_stats(all_data: dict[str, list]) -> pd.DataFrame:
    rows = []
    for key, records in all_data.items():
        pred_all = np.concatenate([r["pred_hu"] for r in records])
        gt_all   = np.concatenate([r["gt_hu"]   for r in records])

        gt_t  = torch.from_numpy(gt_all)
        pred_t = torch.from_numpy(pred_all)

        for tissue, (lo, hi) in TISSUES.items():
            mask = tissue_mask(gt_t, lo, hi).numpy()
            if mask.sum() == 0:
                continue
            stats = hu_errors(pred_all[mask], gt_all[mask])
            rows.append({
                "model"  : key,
                "tissue" : tissue,
                "n_pixels": int(mask.sum()),
                **stats,
            })

    return pd.DataFrame(rows)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def get_args():
    p = argparse.ArgumentParser(description="HU value distribution & tissue error analysis")
    p.add_argument("--data_root",      type=str, default="/home/dministrator/s2025")
    p.add_argument("--ckpt_base",      type=str, default="checkpoints_임베딩1/stage2_vdm")
    p.add_argument("--vqvae_base",     type=str, default="checkpoints_임베딩1/stage1_vqvae")
    p.add_argument("--output_dir",     type=str, default="eval_results/hu_analysis")
    p.add_argument("--device",         type=int, default=0)
    p.add_argument("--n_sample_steps", type=int, default=200)
    p.add_argument("--batch_size",     type=int, default=4)
    p.add_argument("--num_workers",    type=int, default=4)
    p.add_argument("--val_ratio",      type=float, default=0.2)
    p.add_argument("--seed",           type=int, default=42)
    p.add_argument("--keys", nargs="+", default=None,
                   help="평가할 모델 key 목록 (기본: 전체 8개). "
                        "예: --keys uvit_n1_cpr4 uvit_n5_cpr4")
    return p.parse_args()


def main():
    args   = get_args()
    device = torch.device(f"cuda:{args.device}" if torch.cuda.is_available() else "cpu")
    set_determinism(seed=args.seed)
    out = pathlib.Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    configs = get_configs(args.keys)
    print(f"분석 대상 모델: {[c['key'] for c in configs]}")

    all_data: dict[str, list] = {}
    for cfg in configs:
        print(f"\n>>> {cfg['key']}")
        try:
            loaded  = load_for_hu(
                cfg, args.data_root, args.ckpt_base, args.vqvae_base,
                device, args.val_ratio, args.seed, args.batch_size, args.num_workers,
            )
            records = collect_hu(cfg, loaded, device, args.n_sample_steps)
            all_data[cfg["key"]] = records
        except Exception as e:
            print(f"  [건너뜀] {e}")

    if not all_data:
        print("분석 결과 없음.")
        return

    # ── 히스토그램 ────────────────────────────────────────────────────────
    plot_hu_histograms(all_data, out)

    # ── anatomy별 오차 통계 ───────────────────────────────────────────────
    anat_df = compute_anatomy_stats(all_data)
    anat_path = out / "hu_error_stats.csv"
    anat_df.to_csv(anat_path, index=False)
    print(f"[저장] {anat_path}")
    print(anat_df.to_string(index=False))

    # ── 조직별 오차 통계 ──────────────────────────────────────────────────
    tissue_df = compute_tissue_stats(all_data)
    tissue_path = out / "hu_tissue_error_stats.csv"
    tissue_df.to_csv(tissue_path, index=False)
    print(f"\n[저장] {tissue_path}")
    print(tissue_df.to_string(index=False))

    print(f"\n완료: {out}/")


if __name__ == "__main__":
    main()
